package database

var SUPERADMIN_ACL_POLICIES = [][]string{
	{"1", "any-warehouse-input", "GET"},
	{"1", "any-warehouse-input", "POST"},
	{"1", "any-warehouse-input", "PATCH"},
	{"1", "any-warehouse-input", "DELETE"},
	{"1", "any-warehouse-output", "GET"},
	{"1", "any-warehouse-output", "POST"},
	{"1", "any-warehouse-output", "PATCH"},
	{"1", "any-warehouse-output", "DELETE"},
	{"1", "any-warehouse-return", "GET"},
	{"1", "any-warehouse-return", "POST"},
	{"1", "any-warehouse-return", "PATCH"},
	{"1", "any-warehouse-return", "DELETE"},
	{"1", "any-warehouse-writeoff", "GET"},
	{"1", "any-warehouse-writeoff", "POST"},
	{"1", "any-warehouse-writeoff", "PATCH"},
	{"1", "any-warehouse-writeoff", "DELETE"},
	{"1", "reference-books-users", "GET"},
	{"1", "reference-books-users", "POST"},
	{"1", "reference-books-users", "PATCH"},
	{"1", "reference-books-users", "DELETE"},
	{"1", "reference-books-projects", "GET"},
	{"1", "reference-books-projects", "POST"},
	{"1", "reference-books-projects", "PATCH"},
	{"1", "reference-books-projects", "DELETE"},
	{"1", "reference-books-workers", "GET"},
	{"1", "reference-books-workers", "POST"},
	{"1", "reference-books-workers", "PATCH"},
	{"1", "reference-books-workers", "DELETE"},
	{"1", "reference-books-materials", "GET"},
	{"1", "reference-books-materials", "POST"},
	{"1", "reference-books-materials", "PATCH"},
	{"1", "reference-books-materials", "DELETE"},
}
